name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
    - uses: browser-actions/setup-geckodriver@latest
      run: geckodriver& E2E_SMARTCAR_CLIENT_ID=${{secrets.E2E_SMARTCAR_CLIENT_ID}} E2E_SMARTCAR_CLIENT_ID=${{secrets.E2E_SMARTCAR_CLIENT_SECRET}} E2E_SMARTCAR_REDIRECT_URI=${{secrets.E2E_SMARTCAR_REDIRECT_URI}} cargo test -- --nocapture
