name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: browser-actions/setup-geckodriver@latest
    - run: geckodriver --version
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: ${{secrets.E2E_SMARTCAR_CLIENT_ID}} ${{secrets.E2E_SMARTCAR_CLIENT_SECRET}} ${{secrets.E2E_SMARTCAR_REDIRECT_URI}} cargo test --verbose
