name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: browser-actions/setup-geckodriver@latest
      - name: Run tests
        run: DISPLAY=:0\
          MOZ_HEADLESS=1\
          geckodriver --port 4444&\
          E2E_SMARTCAR_CLIENT_ID=${{secrets.E2E_SMARTCAR_CLIENT_ID}}\
          E2E_SMARTCAR_CLIENT_SECRET=${{secrets.E2E_SMARTCAR_CLIENT_SECRET}}\
          E2E_SMARTCAR_REDIRECT_URI=${{secrets.E2E_SMARTCAR_REDIRECT_URI}}\
          cargo test

  build:
    name: build crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
